import { useState } from "react";
import {
  ArrowLeft, ArrowRight, BarChart3, Bot, ChevronLeft, FileText, FileUp,
  GitCompareArrows, Home, Info, LogIn, Menu, Send, Sparkles, Upload,
} from "lucide-react";

const features = [
  { number: "01", name: "Upload reports", Icon: FileUp, tone: "amber", description: "Add annual reports and financial statements to your secure workspace.", hint: "PDF, CSV, XLSX supported" },
  { number: "02", name: "Ask your reports", Icon: Bot, tone: "emerald", description: "Get clear, source-backed answers from the documents you upload.", hint: "Answers cite report pages" },
  { number: "03", name: "Visualize trends", Icon: BarChart3, tone: "violet", description: "Turn key financial metrics into focused, decision-ready visualizations.", hint: "Track the numbers that matter" },
  { number: "04", name: "Compare companies", Icon: GitCompareArrows, tone: "cyan", description: "Put companies, periods, and performance side by side in seconds.", hint: "Make better comparisons" },
];

const navItems = [{ label: "Home", Icon: Home }, { label: "Features", Icon: Sparkles }, { label: "Login", Icon: LogIn }, { label: "About", Icon: Info }];

function Workspace({ feature, onBack, onNext }) {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [files, setFiles] = useState([]);
  const [companyA, setCompanyA] = useState("Insight Corp");
  const [companyB, setCompanyB] = useState("Ledger Systems");
  const Icon = feature.Icon;
  const next = features[Number(feature.number) % features.length];

  const renderTool = () => {
    if (feature.number === "01") return <div className="tool-surface flex min-h-[340px] flex-col items-center justify-center border-dashed text-center">
      <div className="icon-box amber size-14"><Upload size={25} /></div><h3 className="mt-5 text-lg font-medium">Drop financial reports here</h3>
      <p className="mt-2 max-w-sm text-sm leading-6 text-zinc-500">Upload the reports you want InsightLedger to index and analyze.</p>
      <label className="mt-6 cursor-pointer rounded-xl bg-amber-300 px-4 py-3 text-sm font-semibold text-zinc-950 transition hover:bg-amber-200">Choose files<input className="hidden" type="file" multiple accept=".pdf,.csv,.xlsx" onChange={(event) => setFiles([...event.target.files])} /></label>
      {files.length > 0 && <div className="mt-5 flex flex-wrap justify-center gap-2">{files.map((file) => <span key={file.name} className="rounded-lg border border-amber-300/20 bg-amber-300/10 px-3 py-2 text-xs text-amber-100"><FileText className="mr-2 inline" size={13} />{file.name}</span>)}</div>}
    </div>;
    if (feature.number === "02") return <div className="tool-surface min-h-[340px] p-5 sm:p-7"><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4 text-sm leading-6 text-zinc-400">Ask a question about uploaded reports. InsightLedger will return a source-grounded answer with report citations.</div>
      {answer && <div className="mt-4 rounded-xl border border-emerald-300/15 bg-emerald-300/[0.06] p-5 text-sm leading-6 text-zinc-200"><span className="mb-2 block text-xs font-semibold uppercase tracking-wider text-emerald-300">InsightLedger</span>{answer}<p className="mt-3 text-xs text-zinc-500">Source: FY 2025 annual report · page 42</p></div>}
      <form className="mt-5 flex gap-2" onSubmit={(event) => { event.preventDefault(); if (question.trim()) setAnswer("Based on the uploaded financial statements, the reported trend is positive. Connect this interface to the API to receive answers grounded in your report content."); }}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about revenue, margins, or risks..." className="min-w-0 flex-1 rounded-xl border border-white/[0.1] bg-zinc-950 px-4 text-sm outline-none transition placeholder:text-zinc-600 focus:border-emerald-300/50" /><button className="grid size-11 place-items-center rounded-xl bg-emerald-300 text-zinc-950"><Send size={17} /></button></form>
    </div>;
    if (feature.number === "03") return <div className="tool-surface min-h-[340px] p-6 sm:p-8"><div className="flex items-end justify-between"><div><p className="text-xs uppercase tracking-wider text-zinc-500">Revenue growth</p><p className="mt-1 text-3xl font-semibold">$2.84B</p></div><span className="rounded-lg bg-emerald-300/10 px-3 py-2 text-sm text-emerald-300">+18.4%</span></div><div className="mt-10 flex h-44 items-end gap-3 border-b border-l border-white/[0.1] px-4 pt-5">{[38, 54, 48, 72, 66, 88, 100].map((height, index) => <div key={height} className="group relative flex-1 rounded-t-md bg-gradient-to-t from-violet-500/40 to-violet-300" style={{ height: `${height}%` }}><span className="absolute -bottom-6 left-1/2 -translate-x-1/2 text-[10px] text-zinc-600">Q{index + 1}</span></div>)}</div><p className="mt-10 text-sm text-zinc-500">Choose a metric and date range to generate charts from your verified report data.</p></div>;
    return <div className="tool-surface min-h-[340px] p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium uppercase tracking-wider text-zinc-500">Company A<select value={companyA} onChange={(event) => setCompanyA(event.target.value)} className="mt-2 block w-full rounded-xl border border-white/[0.1] bg-zinc-950 p-3 text-sm normal-case tracking-normal text-zinc-200 outline-none"><option>Insight Corp</option><option>Northstar Holdings</option></select></label><label className="text-xs font-medium uppercase tracking-wider text-zinc-500">Company B<select value={companyB} onChange={(event) => setCompanyB(event.target.value)} className="mt-2 block w-full rounded-xl border border-white/[0.1] bg-zinc-950 p-3 text-sm normal-case tracking-normal text-zinc-200 outline-none"><option>Ledger Systems</option><option>Frontier Capital</option></select></label></div><div className="mt-7 grid overflow-hidden rounded-xl border border-white/[0.08] text-sm"><div className="grid grid-cols-3 bg-white/[0.04] px-4 py-3 text-xs uppercase tracking-wider text-zinc-500"><span>Metric</span><span>{companyA}</span><span>{companyB}</span></div>{[["Revenue", "$2.84B", "$2.39B"], ["Operating margin", "24.6%", "21.8%"], ["Free cash flow", "$610M", "$472M"]].map((row) => <div key={row[0]} className="grid grid-cols-3 border-t border-white/[0.06] px-4 py-4 text-zinc-300">{row.map((cell) => <span key={cell}>{cell}</span>)}</div>)}</div></div>;
  };

  return <section className="relative flex min-h-screen flex-col justify-center py-12"><button onClick={onBack} className="absolute left-0 top-7 inline-flex items-center gap-2 text-sm text-zinc-500 transition hover:text-white"><ArrowLeft size={16} /> All features</button><div className="mx-auto w-full max-w-4xl"><div className="flex items-start justify-between gap-5"><div><div className={`icon-box ${feature.tone}`}><Icon size={20} /></div><p className="mt-5 text-xs font-semibold uppercase tracking-[0.2em] text-zinc-500">{feature.number} · InsightLedger</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{feature.name}</h1><p className="mt-3 max-w-2xl text-base text-zinc-400">{feature.description}</p></div><button onClick={onNext} className="mt-12 inline-flex shrink-0 items-center gap-2 rounded-xl bg-emerald-300 px-4 py-3 text-sm font-semibold text-zinc-950 transition hover:bg-emerald-200">Next<span className="hidden sm:inline">: {next.name}</span><ArrowRight size={16} /></button></div><div className="mt-9">{renderTool()}</div></div></section>;
}

export default function App() {
  const [railOpen, setRailOpen] = useState(true);
  const [activeFeature, setActiveFeature] = useState(null);
  const openFeature = (index) => setActiveFeature(index);
  return <main className="min-h-screen overflow-hidden bg-[#090b0d] text-zinc-100 selection:bg-emerald-300 selection:text-zinc-950"><aside className={`fixed inset-y-0 left-0 z-20 border-r border-white/[0.07] bg-[#0c0f11]/95 backdrop-blur-xl transition-all duration-300 ${railOpen ? "w-[72px]" : "w-0 overflow-hidden border-r-0"}`}><div className="flex h-full flex-col items-center py-5"><div className="grid size-9 place-items-center rounded-xl bg-emerald-300 text-zinc-950"><BarChart3 size={18} strokeWidth={2.5} /></div><nav className="my-auto flex flex-col gap-2 rounded-full border border-white/[0.1] bg-white/[0.025] p-2 shadow-2xl">{navItems.map(({ label, Icon }, index) => <button key={label} title={label} onClick={() => index === 1 && document.getElementById("features")?.scrollIntoView({ behavior: "smooth" })} className={`grid size-10 place-items-center rounded-full transition ${index === 0 ? "bg-white text-zinc-950" : "text-zinc-500 hover:bg-white/[0.09] hover:text-zinc-100"}`}><Icon size={17} strokeWidth={index === 0 ? 2.4 : 1.8} /></button>)}</nav><button onClick={() => setRailOpen(false)} title="Hide rail" className="grid size-10 place-items-center rounded-full border border-white/[0.1] bg-white/[0.025] text-zinc-500 transition hover:border-emerald-300/40 hover:text-emerald-200"><ChevronLeft size={18} /></button></div></aside>{!railOpen && <button onClick={() => setRailOpen(true)} title="Show rail" className="fixed bottom-5 left-5 z-30 grid size-10 place-items-center rounded-full border border-white/[0.1] bg-[#0c0f11] text-zinc-400 transition hover:text-white"><Menu size={18} /></button>}<section className={`relative min-h-screen transition-[padding] duration-300 ${railOpen ? "pl-[72px]" : "pl-0"}`}><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_52%_14%,rgba(36,88,73,.16),transparent_38%)]" /><div className="relative mx-auto flex min-h-screen max-w-6xl flex-col px-6 sm:px-10">{activeFeature !== null ? <Workspace feature={features[activeFeature]} onBack={() => setActiveFeature(null)} onNext={() => setActiveFeature((activeFeature + 1) % features.length)} /> : <Landing openFeature={openFeature} />}</div></section></main>;
}

function Landing({ openFeature }) { return <div className="mx-auto flex w-full max-w-5xl flex-1 flex-col justify-center py-12"><div className="mb-10 text-center"><p className="mb-4 text-xs font-semibold uppercase tracking-[0.34em] text-emerald-300/80">InsightLedger · AI analysis workspace</p><h1 className="text-balance text-4xl font-semibold tracking-[-0.045em] text-zinc-50 sm:text-5xl">AI for Annual Reports <span className="text-zinc-500">&</span> Financial Statements</h1><p className="mx-auto mt-5 max-w-xl text-pretty text-base leading-7 text-zinc-400">Bring complex financial documents into one focused surface. Understand the numbers, then act on them.</p></div><div id="features" className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{features.map((feature, index) => { const Icon = feature.Icon; return <button key={feature.name} onClick={() => openFeature(index)} className="feature-card group relative min-h-[245px] overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.045] p-6 text-left transition duration-300 hover:-translate-y-1 hover:border-white/[0.18] hover:bg-white/[0.07]"><span className="absolute right-5 top-5 text-[11px] font-medium tracking-wider text-zinc-600">{feature.number}</span><div className={`icon-box ${feature.tone}`}><Icon size={21} strokeWidth={1.8} /></div><div className="mt-5"><h2 className="text-lg font-medium tracking-tight text-zinc-100">{feature.name}</h2><p className="mt-2 text-[15px] leading-6 text-zinc-400">{feature.description}</p></div><p className="absolute bottom-5 text-[11px] font-medium text-zinc-600 transition group-hover:text-zinc-400">{feature.hint}</p></button>; })}</div><p className="mt-8 text-center text-[10px] font-medium uppercase tracking-[0.14em] text-zinc-600">Select a workspace to begin</p></div>; }
