import { useEffect, useState } from "react";
import {
  ArrowLeft, ArrowRight, BarChart3, Bot, ChevronLeft, FileText, FileUp,
  GitCompareArrows, Home, Info, LogIn, LogOut, Menu, Send, Sparkles, Upload,
} from "lucide-react";
import { auth, firebaseConfigured, signInWithGoogle, signOutUser } from "./firebase";

// Production requests stay in this Vercel project.  A separate URL can still
// be supplied for local development or an intentionally separate API.
const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || (import.meta.env.DEV ? "http://127.0.0.1:8000" : "/api")).replace(/\/$/, "");
const features = [
  { number: "01", name: "Upload reports", Icon: FileUp, tone: "amber", description: "Bring annual reports and financial statements into your secure workspace.", hint: "PDF, TXT, MD supported" },
  { number: "02", name: "Ask your reports", Icon: Bot, tone: "emerald", description: "Get clear, source-backed answers from the documents you upload.", hint: "Answers cite report pages" },
  { number: "03", name: "Visualize trends", Icon: BarChart3, tone: "violet", description: "Turn key financial metrics into focused, decision-ready visualizations.", hint: "Seven chart types available" },
  { number: "04", name: "Compare companies", Icon: GitCompareArrows, tone: "cyan", description: "Put companies, periods, and performance side by side in seconds.", hint: "Compare verified metrics" },
];
const navItems = [{ label: "Home", Icon: Home, tone: "amber" }, { label: "Features", Icon: Sparkles, tone: "emerald" }, { label: "Login", Icon: LogIn, tone: "violet" }, { label: "About", Icon: Info, tone: "cyan" }];
const chartTypes = ["line", "bar", "grouped_bar", "histogram", "piechart", "countplot", "boxplot", "heatmap"];

async function api(path, options = {}) {
  const response = await fetch(`${API_BASE_URL}${path}`, options);
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.detail || "The request could not be completed.");
  return data;
}

function UploadTool() {
  const [file, setFile] = useState(null); const [company, setCompany] = useState(""); const [period, setPeriod] = useState(""); const [status, setStatus] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); if (!file || !company.trim()) return setStatus("Choose a report and enter its company name."); setLoading(true); setStatus(""); try { const form = new FormData(); form.append("file", file); form.append("company", company); form.append("document_type", "annual_report"); if (period) form.append("reporting_period", period); const document = await api("/documents/upload", { method: "POST", body: form }); setStatus(`${document.filename} indexed successfully — ${document.chunk_count} passages ready to analyze.`); } catch (error) { setStatus(error.message); } finally { setLoading(false); } };
  return <form onSubmit={submit} className="tool-surface grid min-h-[350px] gap-5 p-6 sm:grid-cols-2 sm:p-8"><label className="upload-drop sm:col-span-2"><Upload size={25} /><span className="mt-3 text-base font-medium text-zinc-200">{file ? file.name : "Choose a financial report"}</span><span className="mt-1 text-sm text-zinc-500">PDF, TXT, or Markdown — up to your backend’s upload limit</span><input type="file" accept=".pdf,.txt,.md" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label><label className="field-label">Company name<input value={company} onChange={(event) => setCompany(event.target.value)} placeholder="e.g. Insight Corp" /></label><label className="field-label">Reporting period<input value={period} onChange={(event) => setPeriod(event.target.value)} placeholder="e.g. FY 2025" /></label><div className="sm:col-span-2 flex flex-wrap items-center justify-between gap-4"><p className="max-w-lg text-sm leading-6 text-zinc-500">{status || "Your uploaded report stays in your configured local workspace."}</p><button disabled={loading} className="primary-button">{loading ? "Indexing report..." : "Upload & index"}<ArrowRight size={16} /></button></div></form>;
}

function UploadedDocuments() {
  const [documents, setDocuments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const loadDocuments = async () => {
    setLoading(true); setError("");
    try { setDocuments(await api("/documents")); }
    catch (requestError) { setError(requestError.message); }
    finally { setLoading(false); }
  };
  useEffect(() => { loadDocuments(); }, []);
  return <section className="tool-surface overflow-hidden"><div className="flex items-center justify-between gap-4 border-b border-white/[0.08] px-6 py-4"><div><h2 className="text-sm font-semibold text-zinc-100">Uploaded documents</h2><p className="mt-1 text-xs text-zinc-500">Reports available for questions and analysis.</p></div><button type="button" onClick={loadDocuments} disabled={loading} className="text-xs font-semibold text-emerald-300 transition hover:text-emerald-200">{loading ? "Loading..." : "Refresh"}</button></div>{error ? <p className="p-6 text-sm text-rose-300">{error}</p> : loading ? <p className="p-6 text-sm text-zinc-500">Loading uploaded documents...</p> : documents.length === 0 ? <div className="grid min-h-28 place-items-center p-6 text-center text-sm text-zinc-500">No documents uploaded yet. Upload your first report above.</div> : <div className="divide-y divide-white/[0.06]">{documents.map((document) => <div key={document.id} className="flex items-center gap-3 px-6 py-4"><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-amber-300/[0.1] text-amber-300"><FileText size={17} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-zinc-200">{document.filename}</p><p className="mt-1 truncate text-xs text-zinc-500">{document.company}{document.reporting_period ? ` · ${document.reporting_period}` : ""} · {document.chunk_count} passages</p></div><time className="hidden shrink-0 text-xs text-zinc-600 sm:block" dateTime={document.created_at}>{new Date(document.created_at).toLocaleDateString()}</time></div>)}</div>}</section>;
}

function ChatTool() {
  const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); if (!question.trim()) return; setLoading(true); setError(""); try { setAnswer(await api("/ask", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question, top_k: 5 }) })); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  return <div className="tool-surface min-h-[350px] p-5 sm:p-7"><div className="rounded-xl border border-white/[0.07] bg-white/[0.025] p-4 text-sm leading-6 text-zinc-400">Ask a focused question about the reports you have uploaded. Every answer is grounded in retrieved report passages.</div>{answer && <div className="mt-4 rounded-xl border border-emerald-300/15 bg-emerald-300/[0.06] p-5 text-sm leading-6 text-zinc-200"><span className="mb-2 block text-xs font-semibold uppercase tracking-wider text-emerald-300">Answer</span>{answer.answer}<div className="mt-4 flex flex-wrap gap-2">{answer.citations.map((citation) => <span key={`${citation.document_id}-${citation.page}`} className="rounded-lg bg-black/20 px-2 py-1 text-xs text-zinc-400">{citation.filename} · p. {citation.page || "—"}</span>)}</div></div>}{error && <p className="mt-4 text-sm text-rose-300">{error}</p>}<form className="mt-5 flex gap-2" onSubmit={submit}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about revenue, margins, or risks..." /><button disabled={loading} className="grid size-11 shrink-0 place-items-center rounded-xl bg-emerald-300 text-zinc-950"><Send size={17} /></button></form></div>;
}

function VisualizeTool() {
  const [chartType, setChartType] = useState("line"); const [companies, setCompanies] = useState("Insight Corp"); const [metrics, setMetrics] = useState("Revenue"); const [chartUrl, setChartUrl] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(""); try { const result = await api("/visualizations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ chart_type: chartType, companies: companies.split(",").map((item) => item.trim()).filter(Boolean), metrics: metrics.split(",").map((item) => item.trim()).filter(Boolean) }) }); setChartUrl(`${API_BASE_URL}${result.chart_url}`); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  return <div className="tool-surface min-h-[350px] p-6 sm:p-8"><form onSubmit={submit} className="grid gap-4 sm:grid-cols-3"><label className="field-label">Graph type<select value={chartType} onChange={(event) => setChartType(event.target.value)}>{chartTypes.map((type) => <option key={type} value={type}>{type.replace("_", " ")}</option>)}</select></label><label className="field-label">Companies<input value={companies} onChange={(event) => setCompanies(event.target.value)} placeholder="Comma-separated" /></label><label className="field-label">Metrics<input value={metrics} onChange={(event) => setMetrics(event.target.value)} placeholder="Revenue, EBITDA" /></label><div className="sm:col-span-3 flex flex-wrap items-center justify-between gap-4"><p className="text-sm text-zinc-500">Choose line, bar, histogram, pie chart, count plot, box plot, or heatmap.</p><button disabled={loading} className="primary-button">{loading ? "Building chart..." : "Generate chart"}<BarChart3 size={16} /></button></div></form>{error && <p className="mt-5 text-sm text-rose-300">{error}</p>}{chartUrl ? <img className="mt-7 max-h-[420px] w-full rounded-xl border border-white/[0.08] bg-white" src={chartUrl} alt="Generated financial chart" /> : <div className="mt-7 grid h-40 place-items-center rounded-xl border border-dashed border-violet-300/20 bg-violet-300/[0.035] text-sm text-zinc-500">Your generated financial visualization will appear here.</div>}</div>;
}

function CompareTool() {
  const [companyA, setCompanyA] = useState("Insight Corp"); const [companyB, setCompanyB] = useState("Ledger Systems"); const [result, setResult] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(""); try { setResult(await api("/compare", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ company_a: companyA, company_b: companyB }) })); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  return <div className="tool-surface min-h-[350px] p-6 sm:p-8"><form onSubmit={submit} className="grid gap-4 sm:grid-cols-[1fr_1fr_auto]"><label className="field-label">Company A<input value={companyA} onChange={(event) => setCompanyA(event.target.value)} /></label><label className="field-label">Company B<input value={companyB} onChange={(event) => setCompanyB(event.target.value)} /></label><button disabled={loading} className="primary-button self-end">{loading ? "Comparing..." : "Compare"}<GitCompareArrows size={16} /></button></form>{error && <p className="mt-5 text-sm text-rose-300">{error}</p>}{result ? <div className="mt-7 overflow-hidden rounded-xl border border-white/[0.08]"><div className="grid grid-cols-3 bg-white/[0.04] px-4 py-3 text-xs uppercase tracking-wider text-zinc-500"><span>Metric</span><span>{companyA}</span><span>{companyB}</span></div>{Object.entries(result.summary).map(([metric, values]) => <div key={metric} className="grid grid-cols-3 border-t border-white/[0.06] px-4 py-4 text-sm text-zinc-300"><span>{metric}</span><span>{values[companyA] ?? "—"}</span><span>{values[companyB] ?? "—"}</span></div>)}</div> : <div className="mt-7 grid h-40 place-items-center rounded-xl border border-dashed border-cyan-300/20 bg-cyan-300/[0.035] text-sm text-zinc-500">Compare two indexed companies using saved financial metrics.</div>}</div>;
}

function Workspace({ feature, onBack, onNext }) { const Icon = feature.Icon; const next = features[Number(feature.number) % features.length]; const tools = { "01": <div className="space-y-5"><UploadTool /><UploadedDocuments /></div>, "02": <ChatTool />, "03": <VisualizeTool />, "04": <CompareTool /> }; return <section className="relative flex min-h-screen flex-col justify-center py-12"><button onClick={onBack} className="absolute left-0 top-7 inline-flex items-center gap-2 text-sm text-zinc-500 transition hover:text-white"><ArrowLeft size={16} /> All features</button><div className="mx-auto w-full max-w-4xl"><div className="flex items-start justify-between gap-5"><div><div className={`icon-box ${feature.tone}`}><Icon size={20} /></div><p className="mt-5 text-xs font-semibold uppercase tracking-[0.2em] text-zinc-500">{feature.number} · InsightLedger</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{feature.name}</h1><p className="mt-3 max-w-2xl text-base text-zinc-400">{feature.description}</p></div><button onClick={onNext} className="mt-12 inline-flex shrink-0 items-center gap-2 rounded-xl bg-emerald-300 px-4 py-3 text-sm font-semibold text-zinc-950 transition hover:bg-emerald-200">Next<span className="hidden sm:inline">: {next.name}</span><ArrowRight size={16} /></button></div><div className="mt-9">{tools[feature.number]}</div></div></section>; }

export default function App() {
  const [railOpen, setRailOpen] = useState(true); const [activeFeature, setActiveFeature] = useState(null); const [user, setUser] = useState(null); const [authError, setAuthError] = useState(""); const [authLoading, setAuthLoading] = useState(false);
  useEffect(() => { if (!auth) return undefined; return auth.onAuthStateChanged(setUser); }, []);
  const scrollTo = (id) => document.getElementById(id)?.scrollIntoView({ behavior: "smooth" });
  const handleLogin = async () => { setAuthLoading(true); setAuthError(""); try { await signInWithGoogle(); } catch (error) { setAuthError(error.message); } finally { setAuthLoading(false); } };
  const handleNav = (label, index) => { if (label === "Login") return user ? signOutUser() : handleLogin(); setActiveFeature(null); scrollTo(index === 0 ? "home" : label.toLowerCase()); };
  return <main className="min-h-screen overflow-hidden bg-[#090b0d] text-zinc-100 selection:bg-emerald-300 selection:text-zinc-950"><aside className={`fixed inset-y-0 left-0 z-20 border-r border-white/[0.07] bg-[#0c0f11]/95 backdrop-blur-xl transition-all duration-300 ${railOpen ? "w-[72px]" : "w-0 overflow-hidden border-r-0"}`}><div className="flex h-full flex-col items-center py-5"><div className="grid size-9 place-items-center rounded-xl bg-emerald-300 text-zinc-950"><BarChart3 size={18} strokeWidth={2.5} /></div><nav className="my-auto flex flex-col gap-2 rounded-full border border-white/[0.12] bg-gradient-to-b from-emerald-300/[0.11] via-violet-300/[0.07] to-cyan-300/[0.1] p-2 shadow-2xl">{navItems.map(({ label, Icon, tone }, index) => { const isLogin = label === "Login"; const NavIcon = isLogin && user ? LogOut : Icon; const title = isLogin ? (user ? `Logout ${user.displayName || ""}` : authLoading ? "Signing in..." : "Login with Google") : label; return <button key={label} title={title} disabled={isLogin && authLoading} onClick={() => handleNav(label, index)} className={`nav-button ${tone} ${index === 0 ? "active" : ""}`}><NavIcon size={17} strokeWidth={index === 0 ? 2.4 : 1.8} /></button>; })}</nav>{user && <img src={user.photoURL || ""} alt={user.displayName || "Signed in user"} title={user.email || "Signed in"} className="mb-4 size-8 rounded-full border border-emerald-300/40" />}{authError && <span title={authError} className="mb-3 max-w-12 text-center text-[9px] leading-3 text-rose-300">Login error</span>}{!firebaseConfigured && <span title="Add Firebase settings in frontend/.env" className="mb-3 text-[9px] text-amber-300">Auth setup</span>}<button onClick={() => setRailOpen(false)} title="Hide rail" className="grid size-10 place-items-center rounded-full border border-emerald-300/25 bg-emerald-300/[0.08] text-emerald-200 transition hover:bg-emerald-300/20"><ChevronLeft size={18} /></button></div></aside>{!railOpen && <button onClick={() => setRailOpen(true)} title="Show rail" className="fixed bottom-5 left-5 z-30 grid size-10 place-items-center rounded-full border border-emerald-300/25 bg-emerald-300/[0.1] text-emerald-200 transition hover:bg-emerald-300/20"><Menu size={18} /></button>}<section className={`relative min-h-screen transition-[padding] duration-300 ${railOpen ? "pl-[72px]" : "pl-0"}`}><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_52%_14%,rgba(36,88,73,.16),transparent_38%)]" /><div className="relative mx-auto flex min-h-screen max-w-6xl flex-col px-6 sm:px-10">{activeFeature !== null ? <Workspace feature={features[activeFeature]} onBack={() => setActiveFeature(null)} onNext={() => setActiveFeature((activeFeature + 1) % features.length)} /> : <Landing onOpen={(index) => setActiveFeature(index)} />}</div></section></main>;
}

function Landing({ onOpen }) { return <div id="home" className="mx-auto w-full max-w-5xl py-20 sm:py-28"><section className="text-center"><p className="mb-4 text-xs font-semibold uppercase tracking-[0.34em] text-emerald-300/80">InsightLedger · AI analysis workspace</p><h1 className="text-balance text-4xl font-semibold tracking-[-0.045em] text-zinc-50 sm:text-5xl">AI for Annual Reports <span className="text-zinc-500">&</span> Financial Statements</h1><p className="mx-auto mt-5 max-w-xl text-pretty text-base leading-7 text-zinc-400">Bring complex financial documents into one focused surface. Understand the numbers, then act on them.</p></section><section id="features" className="scroll-mt-16 mt-24"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{features.map((feature, index) => { const Icon = feature.Icon; return <button key={feature.name} onClick={() => onOpen(index)} className={`feature-card ${feature.tone} group relative min-h-[245px] overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.045] p-6 text-left transition duration-300 hover:-translate-y-1`}><span className="absolute right-5 top-5 text-[11px] font-medium tracking-wider text-zinc-600">{feature.number}</span><div className={`icon-box ${feature.tone}`}><Icon size={21} strokeWidth={1.8} /></div><div className="mt-5"><h2 className="text-lg font-medium tracking-tight text-zinc-100">{feature.name}</h2><p className="mt-2 text-[15px] leading-6 text-zinc-400">{feature.description}</p></div><p className="absolute bottom-5 text-[11px] font-medium text-zinc-600 transition group-hover:text-zinc-300">{feature.hint}</p></button>; })}</div><div className="mt-16"><SectionIntro eyebrow="The workflow" heading="From report to decision, in four steps" description="Each workspace is designed around a single job, so you can move from raw documents to a clear financial view without losing context." /></div></section><section id="about" className="scroll-mt-16 mt-28 border-t border-white/[0.08] pt-20"><SectionIntro eyebrow="About InsightLedger" heading="A calmer way to work with financial information" description="InsightLedger is a financial-report analysis workspace that combines secure document ingestion, retrieval-assisted AI, comparison, and visualization. It is built to help analysts turn dense disclosures into traceable insights faster." /><div className="mt-10 grid gap-4 sm:grid-cols-3"><Stat label="One workspace" value="Reports, answers & charts" /><Stat label="Grounded answers" value="Sources stay visible" /><Stat label="Flexible analysis" value="7 visualization types" /></div></section></div>; }
function SectionIntro({ eyebrow, heading, description }) { return <div className="mx-auto max-w-2xl text-center"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-emerald-300/80">{eyebrow}</p><h2 className="mt-4 text-3xl font-semibold tracking-tight text-zinc-100 sm:text-4xl">{heading}</h2><p className="mt-4 text-base leading-7 text-zinc-400">{description}</p></div>; }
function Stat({ label, value }) { return <div className="rounded-2xl border border-white/[0.08] bg-white/[0.035] p-5 text-center"><p className="text-xs uppercase tracking-[0.16em] text-zinc-600">{label}</p><p className="mt-2 text-sm text-zinc-300">{value}</p></div>; }
